[project]
name = "sw"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipympl>=0.9.8",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pyserial>=3.5",
    "scipy>=1.16.3",
    "zeroconf>=0.148.0",
]

[tool.ruff]
exclude = ["wulpus/config_package.py", "wulpus/config_package_pro.py"]
