[project]
name = "sw"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipympl>=0.9.2",
    "jupyter>=1.0.0",
    "matplotlib==3.10.1",
    "numpy>=2.2.5",
    "pyserial>=3.5",
    "scipy>=1.15.2",
    "zeroconf>=0.146.5",
]
